# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.5
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

## Mod Properties

mod_id=towerdefenseunits
mod_name=Tower Defense Units
mod_license=All Rights Reserved
mod_version=2.0.0
mod_group_id=com.yellowbrossproductions.yellowbrossextras
mod_authors=Yellowbross Productions, AKA this_is_stupid123
mod_description=Tower Defense Units adds a compilation of new units that can be crafted and used by the Player to defend their base.\n\nThese Units range from offense to defense, with units such as the Turret being for offense and the Angerer for defense.
